name: buildScanPush

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tags:
        default: ""
        type: string
      repository:
        required: true
        type: string
      build_args:
        default: ""
        type: string
      region:
        required: true
        type: string
      dockerfile_path:
        default: "."
        type: string
      exit_on_scan_fail:
        default: 0
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  buildScanPush:
    name: Build scan and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          mask-aws-account-id: false
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ inputs.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-

        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ inputs.repository }}/${{ inputs.image_name}}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=pr
            type=ref,event=branch
            type=raw,${{ inputs.tags }}

        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.meta.outputs.tags }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: ${{ inputs.build_args }}


      # - name: Build the Docker image
      #   run: |
      #     # CONSTRUCT BUILD ARGUMENTS FROM A STRING
      #     if [ -z ${{ inputs.build_args }} ]
      #     then
      #       BUILD_ARGS=""
      #     else
      #       BUILD_ARGS=`echo ${{ inputs.build_args }} | sed -e 's/[ ]/ --build-args /g' | sed -e 's/^/--build-args /'`
      #     fi 

      #     # CONSTRUCT TAGS FROM STRING
      #     image_tags=""
      #     IFS=' ' read -r -a tags <<< ${{ inputs.tags }}
      #     for tag in "${tags[@]}"
      #       do
      #         image_tags=${image_tags}" --tag ${{ inputs.repository }}/${{ inputs.image_name }}:$tag"
      #       done

      #     # EXPORT ONE TAG FOR FURTHER USE IN SCAN
      #     echo "image_tag=${{ inputs.repository }}/${{ inputs.image_name }}:${tag[0]}" >> $GITHUB_ENV

      #     docker build --file ${{ inputs.dockerfile_path }}/Dockerfile ${image_tags} ${BUILD_ARGS} ${{ inputs.dockerfile_path }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: "table"
          exit-code: ${{ inputs.exit_on_scan_fail }}
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: ${{ inputs.build_args }}

      # - name: Push images to AWS ECR
      #   run: |
      #     docker image push --all-tags ${{ inputs.repository }}/${{ inputs.image_name }}
