name: buildScanPush

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tags:
        default: "latest"
        type: string
      repository:
        required: true
        type: string
      build_args:
        default: ""
        type: string
      region:
        required: true
        type: string
      dockerfile_path:
        default: "."
        type: string
      exit_on_scan_fail:
        default: 0
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    name: Build scan and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          mask-aws-account-id: false
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build the Docker image
        run: |
          if [ -z ${{ inputs.build_args }} ]
          then
            BUILD_ARGS=""
          else
            BUILD_ARGS=`echo ${{ inputs.build_args }} | sed -e 's/[ ]/ --build-args /g' | sed -e 's/^/--build-args /'`
          fi 

          image_tags=""
          IFS=' ' read -r -a tags <<< ${{ inputs.tags }}
          for tag in "${tags[@]}"
            do
              image_tags=${image_tags}" --tag ${{ inputs.repository }}/${{ inputs.image_name }}:$tag"
            done

          # Export first tag for image scan
          echo "image_tag=${{ inputs.repository }}/${{ inputs.image_name }}:${tag[0]}" >> $GITHUB_ENV

          docker build --file ${{ inputs.dockerfile_path }}/Dockerfile ${image_tags} ${BUILD_ARGS} ${{ inputs.dockerfile_path }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.image_tag }}"
          format: "table"
          exit-code: ${{ inputs.exit_on_scan_fail }}
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push tag to AWS ECR
        run: |
          docker image push --all-tags ${{ inputs.repository }}/${{ inputs.image_name }}
