name: Create Preview environment

on:
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string
jobs:        
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        id: validate
        run: |
          if [[ '${{ inputs.ref_name }}' =~ ^[0-9A-Za-z\-]*[^\-]$ ]]; then
            echo "::set-output name=valid::true"
          else
            echo 'Branch name should contain only - and alfa-numerics. Failing to do this will cause issues with k8s namespace and container image creation. Please refer to the documentation - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/'
            echo "::set-output name=valid::false"
          fi

  update_pr:
    needs: validate
    runs-on: ubuntu-latest
    if: steps.validate.outputs.valid == 'true'
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Share preview link in PR comments
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            'Check the deployed **micro-application** k8s preview at [preview](https://dash-${{ github.head_ref }}.qa.cloud.adjust.com/datascape/credentials/)!🚀'
            'Check the deployed **storybook** k8s preview at [storybook](https://dash-${{ github.head_ref }}.qa.cloud.adjust.com/datascape/storybook/)!🚀'
          repo-token: ${{ secrets.AUTOMATE_GITHUB_ACCESS_TOKEN }}
