name: Uninstall application

on:
  workflow_call:
    inputs:
      releases:
        description: "Release name"
        type: string
        required: true
      region:
        description: "Region to deploy the application to"
        default: "eu-central-1"
        type: string
      cluster:
        description: "Cluster to deploy the application to"
        default: ""
        required: true
        type: string
      namespace:
        description: "Namespace to which app will be deployed to or the workspace name"
        default: ""
        required: true
        type: string
      destroy_namespace:
        description: "Clean up namespace"
        default: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  run:
    name: Destroying application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        releases: "${{fromJSON(inputs.releases)}}"
    steps:

      - name: test
        run: |
          echo ${{ inputs.releases }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
        
      - name: Generate a kubeconfig for Amazon EKS
        run: |
          aws eks --region ${{ inputs.region }} update-kubeconfig --name ${{ inputs.cluster }}

      - name: '${{ matrix.releases }}'
        run: |
          helm uninstall ${{ matrix.releases }} --namespace ${{ inputs.namespace }}
          kubectl get namespace ${{ inputs.namespace }}
      - name: Remove namespace
        if: inputs.destroy_namespace
        run: |
          if kubectl get namespace ${{ inputs.namespace }};then
            kubectl delete namespace ${{ inputs.namespace }}
          fi

