name: Destroy K8S Preview Environment

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
    secrets:
      githubToken:
        required: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        id: validate
        run: |
          if [[ '${{ inputs.ref_name }}' =~ ^[0-9A-Za-z\-]*[^\-]$ ]]; then
            echo "::set-output name=valid::true"
          else
            echo 'Branch name should contain only - and alfa-numerics. Failing to do this will cause issues with k8s namespace and container image creation. Please refer to the documentation - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/'
            echo "::set-output name=valid::false"
          fi

  destroy:
    runs-on: ubuntu-latest
    if: needs.validate.outputs.valid == 'true'
    needs: validate
    steps:
      - name: Preview
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.githubToken }}
          repository: adjust/dashboard-k8s
          event-type: destroy_preview
          client-payload: '{"app": "${{ inputs.appName }}", "branch": "${{ github.head_ref }}","namespace": "${{ github.head_ref }}", "cluster": "qa-eks", "releases": ["mfe-shell", "mfe-layout", "dashboard-ptl", "dashboard-experience", "dashboard-credentials", "translations", "control-center", "dashboard-ui", "conversion-value-manager"]}'
