name: Storybook Cleanup

on:
  workflow_call:
    secrets:
      githubToken:
        required: true
      ansibleVaultPassword:
        required: true
      sshKey:
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  ANSIBLE_VAULT_PASSWORD: ${{ secrets.ansibleVaultPassword }}
  GITHUB_TOKEN: ${{ secrets.githubToken }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Clone cc-ansible
        uses: actions/checkout@v3
        with:
          repository: adjust/cc-ansible
          token: ${{ secrets.githubToken }}

      - name: Read known_hosts.txt
        id: known_hosts
        uses: andstor/file-reader-action@v1
        with:
          path: 'known_hosts.txt'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.sshKey }}
          known_hosts: ${{ steps.known_hosts.outputs.contents }}
          config: |
            Host *.adjust.com
              User acquired

      - name: Add slugs to env
        uses: rlespinasse/github-slug-action@3.6.0

      - name: 'Destroy: branch storybook'
        id: destroy_branch_storybook
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: timeout
          command: ansible-playbook -vvv -i staging playbooks/frontend/dashexp_storybook.yml -e branch=${{env.GITHUB_HEAD_REF_SLUG_URL}} -t destroy
