name: setupPythonVenv

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      requirements_file:
        required: true
        type: string

    secrets:
      pip_ssh_key:
        required: true

jobs:
  setup_venv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    - name: Cache python virtualenv
      uses: syphar/restore-virtualenv@v1.2
      id: cache-venv
      with:
        requirement_files: '**/requirements*.txt'
      continue-on-error: true

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-venv.outcome == 'success' && steps.cache-venv.outputs.cache-hit != 'true'

    - name: Setup Pip SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.pip_ssh_key }}
      if: steps.cache-venv.outcome == 'success' && steps.cache-venv.outputs.cache-hit != 'true'

    - run: |
        python -m pip install -U pip "setuptools<58"
        python -m pip install -r ${{ inputs.requirements_file }}
